# Generated by Django 5.2.14 on 2026-05-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('quick read', 'Quick Read'), ('older posts', 'Older Posts'), ('recent', 'Recent'), ('trending', 'Trending')], default='recent', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('1', 'Publish'), ('0', 'Draft')], default=0, max_length=1),
        ),
    ]
