# Generated by Django 5.2.14 on 2026-05-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_user_alter_post_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('quick read', 'Quick Read'), ('older posts', 'Older Posts'), ('trending', 'Trending'), ('recent', 'Recent')], default='recent', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Publish')], default=0, max_length=1),
        ),
    ]
