# Generated by Django 5.2.14 on 2026-05-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_section_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('recent', 'Recent'), ('quick_read', 'Quick Read'), ('trending', 'Trending'), ('older_posts', 'Older Posts')], default='recent', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('1', 'Publish'), ('0', 'Draft')], default=0, max_length=1),
        ),
    ]
