# Generated by Django 5.2.14 on 2026-06-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_section_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='catergory',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('quick_read', 'Quick Read'), ('trending', 'Trending'), ('older_posts', 'Older Posts'), ('recent', 'Recent')], default='recent', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('0', 'Draft'), ('1', 'Publish')], default=0, max_length=1),
        ),
    ]
